services:
  db:
    image: postgis/postgis:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ecomap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - database_data:/var/lib/postgresql/data
    secrets:
      - postgres_password

volumes:
 database_data: null

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
