linters-settings:
  goimports:
    local-prefixes: github.com/goncalo-marques/ecomap/server/

linters:
  enable:
    - goimports
    - gofumpt
    - govet
    - stylecheck
    - unconvert
    - unparam
    - misspell
    - whitespace
    - bodyclose
