openapi: "3.0.0"
info:
  version: 1.0.0
  title: EcoMap Rest API
tags:
  - name: Employee
servers:
  - url: https://server-7fzc7ivuwa-ew.a.run.app/api
    description: Production server.
  - url: http://localhost:8080/api
    description: Local server.

paths:
  /employees/signin:
    post:
      summary: Sign in an employee.
      operationId: signInEmployee
      description: Returns a JSON Web Token for the specified username and password.
      tags:
        - Employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignIn"
      responses:
        200:
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JWT"
        400:
          description: Invalid request body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Incorrect credentials.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          $ref: "#/components/responses/InternalServerError"
  /employees/{employeeId}:
    get:
      summary: Get an employee by ID.
      operationId: getEmployeeByID
      description: Returns the employee with the specified identifier.
      tags:
        - Employee
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/EmployeeIdParam"
      responses:
        200:
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        400:
          description: Invalid employee ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        404:
          description: Employee not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          $ref: "#/components/responses/InternalServerError"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    EmployeeIdParam:
      name: employeeId
      in: path
      description: Employee identifier.
      required: true
      schema:
        $ref: "#/components/schemas/UUID"

  schemas:
    UUID:
      type: string
      format: uuid
      example: "9e3a65b0-0579-4203-8112-d09ab3c6b1ff"
    Error:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          enum:
            - bad_request
            - unauthorized
            - not_found
            - internal_server_error
        message:
          type: string

    SignIn:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    JWT:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVcJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiWiBmFtZSI6IkPvaG4gRG9lIiWiaWF0IjOxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssW5c

    EditableEmployee:
      type: object
      required:
        - name
        - dateOfBirth
      properties:
        name:
          type: string
          example: "John Doe"
        dateOfBirth:
          type: string
          format: date
          example: "2006-01-02"
    Employee:
      allOf:
        - $ref: "#/components/schemas/EditableEmployee"
        - type: object
          required:
            - id
          properties:
            id:
              $ref: "#/components/schemas/UUID"

  responses:
    Unauthorized:
      description: Access token is missing or invalid.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Forbidden:
      description: Forbidden.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
