name: CI Android

on:
  pull_request:
    branches:
      - main
    paths:
      - "android/**"

defaults:
  run:
    working-directory: ./android

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Run lint
        run: |
          ./gradlew lint
          cat app/build/reports/lint-results-debug.txt
