name: Deploy production

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "web/**"
      - "server/**"
      - "server.Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      CONTAINER_TAG: ${{ steps.docker-build.outputs.CONTAINER_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          token_format: access_token

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: "${{ vars.REGION }}-docker.pkg.dev"
          username: _json_key
          password: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Build container
        id: docker-build
        run: |
          export CONTAINER_TAG="${{ vars.REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME_SERVER }}:${{ github.sha }}"
          echo $CONTAINER_TAG >> $GITHUB_OUTPUT
          docker build -t $CONTAINER_TAG .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Push container
        run: docker push "${{ needs.build.outputs.CONTAINER_TAG }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.SERVICE_NAME_SERVER }}
          region: ${{ vars.REGION }}
          image: ${{ needs.build.outputs.CONTAINER_TAG }}

      - name: Show deployment URL
        run: echo "Deployed to ${{ steps.deploy.outputs.url }}"
